apiVersion: v1
kind: Service
metadata:
  name: get
  labels:
    app: flask
    component: get
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: flask
    component: get

