apiVersion: v1
kind: Service
metadata:
  name: db-init
  labels:
    app: flask
    component: db-init
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: flask
    component: db-init

