apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-init
  labels:
    app: flask
    component: db-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      component: db-init
  template:
    metadata:
      name: db-init
      labels:
        app: flask
        component: db-init
    spec:
      containers:
      - image: vnikolayenko/db_service:latest_init_create
        envFrom:
        - configMapRef:
            name: env-db-init-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        name: db-init