apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: flask
    component: post
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: flask
    component: post

