apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: flask
    component: db
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: flask
    component: db

