env:
- name: ENVIRONMENT
  value: production
ingress:
  hosts:
    # ingress.hosts[0].host -- Host name for routing traffic.
    - host: production.dimeder.pp.ua
      # ingress.hosts[0].paths -- Array of routable paths.
      paths: ["/"]
