replicaCount: 1

image:
  repository: 074368059797.dkr.ecr.eu-central-1.amazonaws.com/front
  tag: 840d0cb04126efc7ecb57df84d51e828e68d91d1
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: softserve.dimeder.pp.ua
      paths: [/]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

URL_GET: http://get-srv:8081
URL_POST: http://post-srv:8082/a