replicaCount: 1

image:
  repository: 074368059797.dkr.ecr.eu-central-1.amazonaws.com/front
  tag: 840d0cb04126efc7ecb57df84d51e828e68d91d1
  
service:
  type: NodePort
  port: 8080
  targetPort: 8080

URL_GET: http://get-srv:8081
URL_POST: http://post-srv:8082/a