replicaCount: 1

image:
  repository: dimeder13/frontend
  
service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 32080

ingress:
  enabled: false
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

URL_GET: "http://get-srv:8081"
URL_POST: http://post-srv:8082