{{- if .Values.migrate.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "front.fullname" . }}-migrate
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "front.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migrate
{{ include "front.matchLabels" . | indent 8 }}
    spec:
      restartPolicy: Never
      #    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: awsecr-cred
              # {{- toYaml . | nindent 8 }}
              #    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/sh"]
          args: ["-c", "{{ .Values.migrate.command }}"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "front.fullname" $ }}
        {{ with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end -}}
