{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "front.fullname" . }}
  namespace: {{ .Release.Namespace }}
  #namespace: default
  labels:
{{ include "front.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      #nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
{{ include "front.selector" . | indent 4 }}
{{- end }}
