apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    app: flask
    component: back
spec:
  type: NodePort
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: flask
    component: back

