apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: flask
    component: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      component: back
  template:
    metadata:
      name: back
      labels:
        app: flask
        component: back
    spec:
      containers:
      - image: dimeder13/db-service:v1
        envFrom:
        - configMapRef:
            name: env-back-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        name: back